### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create Boiler plate files.
- [x] Create an HTML skeleton
- [x] inside of HTML, create multiple rows that act as y, with class y, containing divs with class x
- [x] Query the DOM for all y and assign the resulting list to $y
- [x] Create a function called Car that takes a sprite (image url) argument, and a x and y argument
- [x] Inside of Car constructer, set this.sprite to argument, and this.x to argument, and this.y to argument
- [x] Inside of Car constructor, create a DOM tree that appends itself to x in y. 
- [x] Inside of constructor, append GameObject.sprite to the corresponding coordinate
